### ISSUE TITLE
HttpMessageDecoder: use of message serializer

### ISSUE THREAD

**Issue by wo80** [jgauffin/Griffin.Framework#6]
In the OnRequestLine method there are checks for ```_messageSerializer == null```, but the message serializer isn't used at all. It's a bit confusing to get a HttpRequestBase in the one case, but a HttpRequest in the other.

Is there a reason for this?

**Comment by jgauffin** [comment]
The purpose is to be able to pass the body just as it is. for instance if you want to build an application server or a proxy it wouldn't be interested in wasting memory on deserializing data when the form will not be used.

At least that's the purpose, maybe I didn't implement that all the way. Please take another look since I've given the HTTP parts a bit more love.

**Comment by wo80** [comment]
Yeah, but I don't see why this should affect what type to return. It's the HttpMessageDecoder that decides if the body should be parsed or not ... just return HttpRequest in any case.

BTW: this is all the cookies fault ;-) When I had a first look at this project, I was casting an ```IClientContext..RequestMessage``` to ```IHttpRequest``` - but it has no cookie collection. Then I was casting to ```HttpRequest```, but was getting a null reference exception (because I hadn't added a body decoder). I then found it was the ```HttpMessageDecoder``` causing the trouble and wondered why it was returning different types ...

**Comment by jgauffin** [comment]
You are of course correct. Design for the most common case. I've removed the base classes and updated the interfaces. How it doesn't cause too much trouble.
